# Generated by Django 4.2.2 on 2023-06-25 17:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100, null=True)),
                ('deskripsi', models.TextField(null=True)),
                ('foto_berita', models.FileField(null=True, upload_to='berita/')),
                ('tanggal_upload', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
            options={
                'db_table': 'berita',
            },
        ),
        migrations.CreateModel(
            name='Kegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100, null=True)),
                ('deskripsi', models.TextField(null=True)),
                ('foto_kegiatan', models.FileField(null=True, upload_to='kegiatan/')),
                ('tanggal_upload', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
            options={
                'db_table': 'kegiatan',
            },
        ),
        migrations.CreateModel(
            name='Modul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tingkat', models.CharField(choices=[('Tingkat 1', 'Tingkat 1'), ('Tingkat 2', 'Tingkat 2'), ('Tingkat 3', 'Tingkat 3')], max_length=255)),
                ('materi', models.CharField(choices=[('Membaca', 'Membaca'), ('Menulis', 'Menulis'), ('Menghitung', 'Menghitung')], max_length=255)),
                ('judul', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('file_modul', models.FileField(upload_to='modul/')),
            ],
            options={
                'db_table': 'materi_modul',
            },
        ),
        migrations.CreateModel(
            name='Pengajuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Menunggu Penilaian', 'Menunggu Penilaian'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak')], max_length=255)),
                ('file_bukti', models.FileField(upload_to='pengajuan/')),
            ],
            options={
                'db_table': 'pengajuan',
            },
        ),
        migrations.CreateModel(
            name='Pengetesan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tingkat', models.CharField(choices=[('Tingkat 1', 'Tingkat 1'), ('Tingkat 2', 'Tingkat 2'), ('Tingkat 3', 'Tingkat 3')], max_length=255)),
                ('materi', models.CharField(choices=[('Membaca', 'Membaca'), ('Menulis', 'Menulis'), ('Menghitung', 'Menghitung')], max_length=255)),
                ('judul', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
            options={
                'db_table': 'pengetesan',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materi', models.CharField(choices=[('Membaca Tingkat 1', 'Membaca Tingkat 1'), ('Membaca Tingkat 2', 'Membaca Tingkat 2'), ('Membaca Tingkat 3', 'Membaca Tingkat 3'), ('Menulis Tingkat 1', 'Menulis Tingkat 1'), ('Menulis Tingkat 2', 'Menulis Tingkat 2'), ('Menulis Tingkat 3', 'Menulis Tingkat 3'), ('Menghitung Tingkat 1', 'Menghitung Tingkat 1'), ('Menghitung Tingkat 2', 'Menghitung Tingkat 2'), ('Menghitung Tingkat 3', 'Menghitung Tingkat 3')], max_length=255)),
                ('judul', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('file_video', models.FileField(upload_to='videos/')),
            ],
            options={
                'db_table': 'materi_video',
            },
        ),
    ]
