# Generated by Django 4.2.2 on 2023-06-25 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guru', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('murid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengajuan',
            name='murid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='murid.murid'),
        ),
        migrations.AddField(
            model_name='pengajuan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
