# Generated by Django 4.2.2 on 2023-06-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengajuan',
            name='status',
            field=models.CharField(choices=[('Menunggu Penilaian', 'Menunggu Penilaian'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak')], default='Menunggu Penilaian', max_length=255),
        ),
    ]
