# Generated by Django 4.2.2 on 2023-06-25 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0003_alter_pengajuan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengajuan',
            name='pengetesan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guru.pengetesan'),
        ),
    ]
