# Generated by Django 4.2.2 on 2023-07-05 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guru', '0004_pengajuan_pengetesan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modul',
            name='tingkat',
        ),
        migrations.AlterField(
            model_name='modul',
            name='materi',
            field=models.CharField(choices=[('Membaca Tingkat 1', 'Membaca Tingkat 1'), ('Membaca Tingkat 2', 'Membaca Tingkat 2'), ('Membaca Tingkat 3', 'Membaca Tingkat 3'), ('Menulis Tingkat 1', 'Menulis Tingkat 1'), ('Menulis Tingkat 2', 'Menulis Tingkat 2'), ('Menulis Tingkat 3', 'Menulis Tingkat 3'), ('Menghitung Tingkat 1', 'Menghitung Tingkat 1'), ('Menghitung Tingkat 2', 'Menghitung Tingkat 2'), ('Menghitung Tingkat 3', 'Menghitung Tingkat 3')], max_length=255),
        ),
    ]
