# Generated by Django 4.2.2 on 2023-06-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Murid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tingkat', models.CharField(choices=[('Tingkat 1', 'Tingkat 1'), ('Tingkat 2', 'Tingkat 2'), ('Tingkat 3', 'Tingkat 3')], max_length=255)),
                ('nama', models.CharField(max_length=30)),
                ('jenis_kelamin', models.CharField(max_length=10)),
                ('tempat_lahir', models.CharField(max_length=20)),
                ('tanggal_lahir', models.DateField()),
                ('anak_ke', models.CharField(max_length=15)),
                ('agama', models.CharField(max_length=15)),
                ('alamat', models.CharField(max_length=40)),
                ('nama_ayah', models.CharField(max_length=30)),
                ('nama_ibu', models.CharField(max_length=30)),
                ('no_handphone', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'murid',
            },
        ),
    ]
