# Generated by Django 4.2.2 on 2023-06-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('murid', '0003_alter_murid_tingkat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='murid',
            name='tingkat',
        ),
        migrations.AddField(
            model_name='murid',
            name='membaca',
            field=models.CharField(choices=[('Membaca Tingkat 1', 'Membaca Tingkat 1'), ('Membaca Tingkat 2', 'Membaca Tingkat 2'), ('Membaca Tingkat 3', 'Membaca Tingkat 3')], default='Membaca Tingkat 1', max_length=50),
        ),
        migrations.AddField(
            model_name='murid',
            name='menghitung',
            field=models.CharField(choices=[('Menghitung Tingkat 1', 'Menghitung Tingkat 1'), ('Menghitung Tingkat 2', 'Menghitung Tingkat 2'), ('Menghitung Tingkat 3', 'Menghitung Tingkat 3')], default='Menghitung Tingkat 1', max_length=50),
        ),
        migrations.AddField(
            model_name='murid',
            name='menulis',
            field=models.CharField(choices=[('Menulis Tingkat 1', 'Menulis Tingkat 1'), ('Menulis Tingkat 2', 'Menulis Tingkat 2'), ('Menulis Tingkat 3', 'Menulis Tingkat 3')], default='Menulis Tingkat 1', max_length=50),
        ),
    ]
