# Generated by Django 4.2.2 on 2023-06-25 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('murid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('confirm_password', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('User', 'User'), ('Admin', 'Admin'), ('Guru', 'Guru')], default='User', max_length=10)),
            ],
            options={
                'db_table': 'pengguna',
            },
        ),
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=15)),
                ('nama', models.CharField(max_length=30)),
                ('alamat', models.CharField(max_length=40)),
                ('no_handphone', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'guruu',
            },
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id_pembayaran', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('token_pembayaran', models.CharField(default=uuid.uuid4, editable=False, max_length=50)),
                ('nama', models.CharField(max_length=255)),
                ('jenis_bank', models.CharField(max_length=255)),
                ('bukti_transfer', models.FileField(upload_to='bukti_transfer/')),
                ('status_pembayaran', models.CharField(choices=[('Menunggu', 'Menunggu'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak')], default='Menunggu', max_length=255)),
                ('tanggal_pembayaran', models.DateTimeField(auto_now_add=True)),
                ('murid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='murid.murid')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pembayaran',
            },
        ),
    ]
